model:
  default: z-ai/glm-5.3-flash
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
agent:
  reasoning_effort: minimal
browser:
  cloud_provider: local
command_allowlist:
  - execute_code
  - script execution via -e/-c flag
  - script execution via heredoc
platform_toolsets:
  telegram:
    - browser
    - clarify
    - code_execution
    - computer_use
    - connections
    - cronjob
    - delegation
    - file
    - homeassistant
    - image_gen
    - memory
    - session_search
    - skills
    - terminal
    - todo
    - tts
    - vision
    - web
  cli:
    - browser
    - clarify
    - code_execution
    - computer_use
    - connections
    - cronjob
    - delegation
    - file
    - image_gen
    - memory
    - session_search
    - skills
    - terminal
    - todo
    - tts
    - vision
    - web
